/* ACCADEMIA ACCENTURE 2.0 - Turma 5 - Data Engineer
 * Projeto Final
 * Grupo 1: DataRangers
 * 
 * Script para criação do DataBase com o Schema para armazenar
 * os registros de países e os dados de COVID-19 por todo o mundo.
 */

CREATE DATABASE DB_COVID_NINETEEN;

USE DB_COVID_NINETEEN;

CREATE TABLE COUNTRY (
	ID		INT			NOT NULL IDENTITY(1, 1),
	NAME	VARCHAR(50)	NOT NULL,
	ISO2	VARCHAR(2)	NOT NULL,
	SLUG	VARCHAR(60) NOT NULL,
	CONSTRAINT PK_COUNTRY PRIMARY KEY (ID)
);

CREATE TABLE COUNTRY_COVID_DAILY (
	ID					INT		NOT NULL IDENTITY(1, 1),
	ID_COUNTRY			INT		NOT NULL,
	CONFIRMED_CASES		INT		NOT NULL, 
	DEATHS				INT		NOT NULL,
	DATE				DATE	NOT NULL,
	CONSTRAINT PK_COUNTRY_COVID_DAILY PRIMARY KEY (ID),
	CONSTRAINT FK_COUNTRY_COVID_DAILY_COUNTRY FOREIGN KEY (ID_COUNTRY)
	REFERENCES COUNTRY (ID)
);

CREATE TABLE COUNTRY_COVID_SUMMARY (
	ID					INT		NOT NULL IDENTITY(1, 1),
	ID_COUNTRY			INT		NOT NULL,
	TOTAL_CONFIRMED		INT		NOT NULL,
	TOTAL_DEATHS		INT		NOT NULL,
	CONSTRAINT PK_COUNTRY_COVID_SUMMARY PRIMARY KEY (ID),
	CONSTRAINT FK_COUNTRY_COVID_SUMMARY_COUNTRY FOREIGN KEY (ID_COUNTRY)
	REFERENCES COUNTRY (ID)
);
